language: go
dist: xenial
sudo: required

os: linux
services:
- docker
env:
  global:
  - TAG=${TRAVIS_TAG:=${TRAVIS_COMMIT}}
  - GH_URL=https://sredevopsdev.github.io/Kafka-Connect-K8s-Operator
  matrix:
  - CLUSTER=openshift
  - CLUSTER=kubernetes

go_import_path: github.com/sredevopsdev/kafka-connect-k8s-operator

cache:
  directories:
  - $HOME/.cache/go-build
go:
- 1.13.x
