apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect-k8s-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-connect-k8s-operator
  template:
    metadata:
      labels:
        name: kafka-connect-k8s-operator
    spec:
      serviceAccountName: kafka-connect-k8s-operator
      containers:
      - name: kafka-connect-k8s-operator
        # Replace this with the built image name
        image: docker.io/kafkaconnect/k8s-operator:latest
        command:
        - Kafka-Connect-K8s-Operator
        imagePullPolicy: Always
        ports:
        - containerPort: 6443
          name: https
        - containerPort: 8080
          name: http
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "kafka-connect-k8s-operator"

---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta2.custom.metrics.k8s.io
spec:
  service:
    name: kafka-connect-k8s-operator-svc
    namespace: default
  group: custom.metrics.k8s.io
  version: v1beta2
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 200

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-k8s-operator-svc
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  - name: http
    port: 80
    targetPort: 8080
  selector:
    name: kafka-connect-k8s-operator
